M48
; DRILL file {KiCad (6.0.11)} date Tue Mar 14 15:00:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-14T15:00:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.35Y-0.8816
X4.35Y-1.1572
X4.83Y-0.8816
X4.83Y-1.1572
T2
X3.4Y-1.0
X3.4Y-3.7
X6.5Y-1.0
X6.5Y-3.7
T0
M30
