M48
; DRILL file {KiCad (6.0.11)} date Tue Feb 28 10:49:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-28T10:49:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.8224Y-2.9823
X5.8224Y-3.2579
X6.671Y-3.0086
X6.671Y-3.2842
T2
X2.9Y-2.726
X2.9Y-5.5
X7.3Y-2.725
X7.3Y-5.5
T0
M30
